### ISSUE TITLE
Flag to disable the use of ConnQuery method

### ISSUE THREAD

**Issue by anze-brvar-cookie** [cockroachdb/copyist#25]
We found out that some drivers don't implement `QueryContext` method and this case is not covered in copyist right now.

What happens is that on record, the driver returns `ErrSkip` if the underlying driver does not support that method and fallbacks to `ConnPrepare` method instead (as documented [here](https://cs.opensource.google/go/go/+/master:src/database/sql/driver/driver.go;l=217)). `ConnPrepare` is correctly recorded. The issue is that on replay the `proxyConn` [always supports](https://github.com/cockroachdb/copyist/blob/master/conn.go#L178) `ConnQuery` (and expects it in `VerifyRecordWithStringArg()` which fails with `unexpected call to ConnQuery`), but it should really fallback to `ConnPrepare` as recorded.

Initially I was trying to fix the `proxyConn.QueryContext` method to check what's implemented on the driver, but it's impossible to check if the driver supports the conn if we don't have the instance of it when replaying.

This behavior was observed for drivers `sqlserver`, `azuresql`, `trino`.

[In this commit](https://github.com/anzebrvar/copyist/commit/836f95a94dc7fac54ec3058c5a346059d2b8d699) I added additional flag to turn off the use of `ConnQuery` used by `proxyConn.QueryContext` introduced in #9. Would be nice if this gets upstream.

**Comment by addshore** [comment]
Just came across this issue while using copyist with MySQL
Using the fork by @anze-brvar-cookie seems to work well for me
Would be great to get it merged!

**Comment by addshore** [comment]
Though it would also be nice to have env var support for this flag

Something like https://github.com/cockroachdb/copyist/blob/b3b04d86deaa0505b4dfc0bd85177d8ef132d804/copyist.go#L58-L62

**Comment by hectorj-thetreep** [comment]
Hi! Do you still have this exact issue?

I just got something similar, but the `ConnQuery`/`ConnExec` calls were recorded.
The issue was that when replaying, the error that was sent back was just a `errors.New("driver: skip fast-path; continue as if unimplemented")` instead of `driver.ErrSkip`

Something like this fixes it: https://github.com/thetreep/copyist/commit/7e3657d056c4654504a78e10f7b5aaaa47cf2928

I don't know if this deserves a separate issue so I'm asking here first.

**Comment by addshore** [comment]
Indeed https://github.com/thetreep/copyist/commit/7e3657d056c4654504a78e10f7b5aaaa47cf2928 also fixes my issue here and is a much more elegant solution!
I'll abandon my PR and would love to see your commit merged, i'm using that commit in my project now
