### ISSUE TITLE
Unable to run migrations with gorm and pgx v5

### ISSUE THREAD

**Issue by dan-j** [cockroachdb/copyist#26]
Using the following dependencies:

```
github.com/cockroachdb/copyist v1.6.0
gorm.io/driver/postgres v1.5.2
gorm.io/gorm v1.25.2
github.com/jackc/pgx/v5 v5.3.1 // indirect
```

Utilising gorm's migrator interface, i.e. `db.Migrator.AutoMigrate(&MyStruct{})`, results in an error like the following:

```
expected 0 arguments, got 1
```

It's took a bit of digging, but what's happening is a query like so is being made with 1 argument: `SELECT * FROM "table" LIMIT 1`, which is invalid since there isn't any `?` delimiters in the query.

This works fine without copyist, and what seems to be happening is that pgx handles special arguments which implement `github.com/jackc/pgx/v5.QueryExecMode`, to determine how the query is executed and then pops it off the args list.

Within the `database/sql` package, `DB.queryDC(...)` makes a call to `driverArgsConnLocked(...)` which converts the args slice to a `[]driver.NamedValue`. This function checks if the underlying connection implements `driver.NamedValueChecker` and if so, delegates handling of each argument. If the connection does not implement this interface, the `defaultCheckNamedValue(...)` function is used, which uses the reflect package to convert the `QueryExecMode` value to a raw `int64`. 

Now pgx receives a `[]driver.NamedValue` and doesn't recognise the arguments implement `QueryExecMode` and it passes the arg with the query, resulting in the error.

# Proposed solution

Implement the `driver.NamedValueChecker` interface and delegate to the underlying connection if it also implements it, otherwise perform the same behaviour of the `database/sql` package.

**Comment by JeffSwenson** [comment]
Thanks for the fix! I merged https://github.com/cockroachdb/copyist/pull/27 and cut a new release that contains the change.
